let step=1,lang='it',availability={};const f=document.getElementById('entryForm'),steps=[...document.querySelectorAll('.form-step')],labs=[...document.querySelectorAll('.steps li')],next=document.getElementById('nextBtn'),prev=document.getElementById('prevBtn'),bar=document.getElementById('progressBar'),cls=f.elements.trialClass,notice=document.getElementById('capacityNotice'),receipt=f.elements.receipt;document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));function setLang(l){lang=l;document.querySelectorAll('[data-it]').forEach(e=>{const v=e.getAttribute('data-'+l);if(v)e.innerHTML=v});document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===l))}const same=document.getElementById('sameHandler'),hs=document.getElementById('handlerSection');function sync(){hs.style.display=same.checked?'none':'block';[['ownerFirstName','handlerFirstName'],['ownerLastName','handlerLastName'],['ownerPhone','handlerPhone'],['ownerEmail','handlerEmail']].forEach(([a,b])=>{f.elements[b].required=!same.checked;if(same.checked)f.elements[b].value=f.elements[a].value})}same.onchange=sync;['ownerFirstName','ownerLastName','ownerPhone','ownerEmail'].forEach(n=>f.elements[n].oninput=sync);sync();async function loadAvailability(){
  if(!window.CONFIG || !window.CONFIG.BACKEND_URL){
    availability={
      'IHT2 – 23/10/2026':{limit:10,confirmed:0,available:10,full:false},
      'HWT TS – 24/10/2026':{limit:10,confirmed:0,available:10,full:false},
      'IHT3 – 24/10/2026':{limit:10,confirmed:0,available:10,full:false},
      'IHT1 – 25/10/2026':{limit:10,confirmed:0,available:10,full:false},
      'NHAT – 25/10/2026':{limit:null,confirmed:0,available:null,full:false}
    };
    updateCap();
    return;
  }
  try{
    const r=await fetch(window.CONFIG.BACKEND_URL+'?action=availability');
    availability=await r.json();
    updateCap();
  }catch(e){}
}
loadAvailability();function updateCap(){const a=availability[cls.value];if(!a){notice.textContent='';return}if(a.limit===null){notice.textContent='NHAT: iscrizioni senza limite.';receipt.required=true}else if(a.full){notice.textContent='Iscrizioni complete – lista d’attesa aperta.';receipt.required=false}else{notice.textContent=a.available+' posti disponibili.';receipt.required=true}}cls.onchange=updateCap;const c=document.getElementById('signatureCanvas'),x=c.getContext('2d');let d=false,signed=false;function p(e){const r=c.getBoundingClientRect(),q=e.touches?e.touches[0]:e;return{x:(q.clientX-r.left)*c.width/r.width,y:(q.clientY-r.top)*c.height/r.height}}function st(e){e.preventDefault();d=true;const q=p(e);x.beginPath();x.moveTo(q.x,q.y)}function dr(e){if(!d)return;e.preventDefault();const q=p(e);x.lineWidth=3;x.lineTo(q.x,q.y);x.stroke();signed=true}['mousedown','touchstart'].forEach(z=>c.addEventListener(z,st,{passive:false}));['mousemove','touchmove'].forEach(z=>c.addEventListener(z,dr,{passive:false}));['mouseup','mouseleave','touchend'].forEach(z=>c.addEventListener(z,()=>d=false));document.getElementById('clearSignature').onclick=()=>{x.clearRect(0,0,c.width,c.height);signed=false};function valid(){for(const a of steps[step-1].querySelectorAll('[required]'))if(!a.checkValidity()){a.reportValidity();return false}if(step===5&&!signed){alert('Firma PSA mancante');return false}return true}function render(){steps.forEach(s=>s.classList.toggle('active',+s.dataset.step===step));labs.forEach((l,i)=>l.classList.toggle('active',i<step));bar.style.width=step*20+'%';prev.style.visibility=step===1?'hidden':'visible';next.textContent=step===5?'Invia iscrizione':'Avanti';if(step===5){const z=new FormData(f);document.getElementById('summary').innerHTML=`<b>Proprietario:</b> ${z.get('ownerFirstName')} ${z.get('ownerLastName')}<br><b>Conduttore:</b> ${z.get('handlerFirstName')} ${z.get('handlerLastName')}<br><b>Cane:</b> ${z.get('dogName')}<br><b>Classe:</b> ${z.get('trialClass')}`}}prev.onclick=()=>{if(step>1){step--;render()}};next.onclick=()=>{if(!valid())return;if(step<5){step++;render()}else submit()};async function file64(input){const q=input.files[0];if(!q)return null;return await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r({name:q.name,mimeType:q.type,data:String(fr.result).split(',')[1]});fr.readAsDataURL(q)})}async function submit(){
if(!window.CONFIG || !window.CONFIG.BACKEND_URL){
  alert('Il sito pubblico è online. Il collegamento alle iscrizioni verrà attivato dopo la configurazione del backend.');
  return;
}
const z=new FormData(f),payload={};for(const[k,v]of z.entries())if(!(v instanceof File))payload[k]=v;['psaAccepted','vaccinationValid','vaccinationInspection','rulesAccepted'].forEach(k=>payload[k]=f.elements[k].checked);payload.signatureData=c.toDataURL('image/png');payload.language=lang;payload.files={receipt:await file64(receipt),pedigree:await file64(f.elements.pedigree),recordBook:await file64(f.elements.recordBook)};const r=await fetch(window.CONFIG.BACKEND_URL,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify(payload)});const j=await r.json();alert(j.ok?'Iscrizione registrata: '+j.code:j.error)}render();